version: '3'

services:
  app:
    build: ./web
    # Laravelのソースコードを格納する
    volumes:
      - ./app:/var/www/html
      - ./web/apache/default.conf:/etc/apache2/sites-enabled/default.conf
    ports:
      - "8081:80"
    # working_dirを設定することで、コンテナに入った時にこのディレクトリから入れる
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: LaravelDB
      MYSQL_ROOT_PASSWORD: password